
jobs:
- job: Flow_Appsec_Job
  # refs/heads/master should be changed to refs/heads/<target_branch>
  condition: eq(variables['build.sourceBranch'], 'refs/heads/master')
  workspace: 
      clean: all
  pool:
      name: Default
      demands:
        - agent.name -equals ec2-agent
  container:
    image: 'convisoappsec.azurecr.io/flowcli'
    endpoint: 'registry-service-connection'
    
  variables:
    FLOW_API_URL: 'https://homologa.conviso.com.br'
    FLOW_PROJECT_CODE: 'Kt5p5zKb_zbth0o0'
    FLOW_API_INSECURE: 'true'
  steps:
    - task: DockerInstaller@0
      displayName: Docker Installer
      inputs:
      dockerVersion: 19.03.6-ce
      releaseType: stable
    - bash: flow --help
    
