trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

container: 
  image: convisoappsec/flowcli

steps:
       
  - script: |
      flow -i deploy create -f env_vars with tag-tracker sort-by time > created_deploy_vars
      source created_deploy_vars
      flow -i sast run --start-commit "$FLOW_DEPLOY_PREVIOUS_VERSION_COMMIT" --end-commit "$FLOW_DEPLOY_CURRENT_VERSION_COMMIT"
      
    env:
      FLOW_API_KEY: $(FLOW_API_KEY)
      FLOW_API_URL: 'https://homologa.conviso.com.br'
      FLOW_PROJECT_CODE: '8qE3Q2w9C6qHGtGt'