
jobs:
- job: Flow_Appsec_Job
  branches:
      include: 
         - outro
  workspace: 
      clean: all
  pool:
      name: Default
      demands:
        - agent.name -equals ec2-agent
  container:
    image: 'convisoappsec.azurecr.io/flowcli'
    endpoint: 'registry-service-connection'
    
  variables:
    FLOW_API_URL: 'https://homologa.conviso.com.br'
    FLOW_PROJECT_CODE: 'Kt5p5zKb_zbth0o0'
    FLOW_API_INSECURE: 'true'
  steps:
    - bash: flow --help
    
