
jobs:
- job: pre_conviso
  pool:
      name: Default
  steps:
     - bash: curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh
     - task: DockerInstaller@0
       displayName: Docker Installer
       inputs:
         dockerVersion: 17.09.0-ce
         releaseType: stable
     - bash: docker --version
     - bash: docker info

# - job: Flow_Appsec_Job
#   # refs/heads/master should be changed to refs/heads/<target_branch>
#   condition: eq(variables['build.sourceBranch'], 'refs/heads/master')
#   dependsOn: pre-conviso
#   workspace: 
#       clean: all
#   pool:
#       name: Default
#       demands:
#         - DOCKER
#   container:
#     image: 'convisoappsec.azurecr.io/flowcli'
#     endpoint: 'registry-service-connection'
    
#   variables:
#     FLOW_API_URL: 'https://homologa.conviso.com.br'
#     FLOW_PROJECT_CODE: 'Kt5p5zKb_zbth0o0'
#     FLOW_API_INSECURE: 'true'
#   steps:

#     - bash: flow --help
    
