version: 0.2

env:
  variables: 
    FLOW_PROJECT_CODE: '2IhoXPKH2rz22LjB'
    FLOW_API_URL: 'https://homologa.conviso.com.br'
  secrets-manager:
    FLOW_API_KEY: FLOW_API_KEY:FLOW_API_KEY
    
phases:
  pre_build:
    commands:
      - ls -ltrah $CODEBUILD_SRC_DIR
      - cd $CODEBUILD_SRC_DIR && git status
      - docker run --rm hello-world
