version: 0.2

env:
  variables: 
    FLOW_PROJECT_CODE: '2IhoXPKH2rz22LjB'
  secrets-manager:
    FLOW_API_KEY: FLOW_API_KEY:FLOW_API_KEY
    
phases:
  pre_build:
    commands:
      - flow sast run -r $CODEBUILD_SRC_DIR
