version: 0.2

env:
  variables: 
    FLOW_PROJECT_CODE: '2IhoXPKH2rz22LjB'
    FLOW_API_URL: 'https://homologa.conviso.com.br'
  secrets-manager:
    FLOW_API_KEY: FLOW_API_KEY:FLOW_API_KEY
    
phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - pip3 install conviso-flowcli
  pre_build:
    commands:
      - deploy_create_output_vars="$(mktemp)"
      - flow deploy create -f env_vars with values > "$deploy_create_output_vars"
      - source "$deploy_create_output_vars"
      - echo "PREVIOUS_COMMIT $FLOW_DEPLOY_PREVIOUS_VERSION_COMMIT"
      - echo "CURRENT_COMMIT $FLOW_DEPLOY_CURRENT_VERSION_COMMIT"
      - flow sast run --start-commit "$FLOW_DEPLOY_PREVIOUS_VERSION_COMMIT" --end-commit "$FLOW_DEPLOY_CURRENT_VERSION_COMMIT"
      - echo "finished."
